#!/usr/bin/env python3
"""
steffi-extract

Decode a base64-encoded ZIP archive and extract its contents to a directory.
Insert the full base64 string into the placeholder variable below and run.
"""

import base64
import os
import zipfile
from io import BytesIO


def main() -> None:
    """Entry point for the steffi-extract script."""
    # Paste the full base64 string between the quotes below
    base64_string = "UEsDBBQAAAAAAP17ClsWd4DZ+wEAAPsBAAAMAAAAcHVic3BlYy55YW1sCm5hbWU6IHN0ZWZmaV93YWtlYXBwCmRlc2NyaXB0aW9uOiBBIHBlcnNvbmFsaXplZCBhbGFybSBjbG9jayBhcHAgZm9yIFN0ZWZmaQp2ZXJzaW9uOiAxLjAuMAoKZW52aXJvbm1lbnQ6CiAgc2RrOiAiPj0yLjEyLjAgPDMuMC4wIgoKZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXI6CiAgICBzZGs6IGZsdXR0ZXIKICBhdWRpb3BsYXllcnM6IF4wLjIwLjEKICBzaGFyZWRfcHJlZmVyZW5jZXM6IF4yLjAuMAogIGZsdXR0ZXJfbG9jYWxfbm90aWZpY2F0aW9uczogXjkuMC4wCiAgcHJvdmlkZXI6IF42LjAuMAogIHZpYnJhdGU6IF4wLjAuNCAgICAgICAgICAgICAjIEZvciBoYXB0aWMgZmVlZGJhY2sKICBjb25mZXR0aTogXjAuNi4wICAgICAgICAgICAgIyBGb3IgY29uZmV0dGkgYW5pbWF0aW9ucwoKZmx1dHRlcjoKICB1c2VzLW1hdGVyaWFsLWRlc2lnbjogdHJ1ZQogIGFzc2V0czoKICAgIC0gYXNzZXRzL2ltYWdlcy8KICAgIC0gYXNzZXRzL3NvdW5kcy8KICAgIC0gYXNzZXRzL3RleHRzLwogICAgUEsDBBQAAAAAAP17ClujOkrArwEAAK8BAAAYAAAAbGliL3V0aWxzL2NvbnN0YW50cy5kYXJ0CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnOwoKY29uc3QgQ29sb3IgbW9vZERlZXBQdXJwbGUgPSBDb2xvcigweEZGNEIwMDgyKTsgLy8gV29yc3QgbW9vZApjb25zdCBDb2xvciBtb29kTGlnaHRQdXJwbGUgPSBDb2xvcigweEZGODAwMEZGKTsKY29uc3QgQ29sb3IgbW9vZE1pZFBpbmsgPSBDb2xvcigweEZGQjAwMDdGKTsKY29uc3QgQ29sb3IgbW9vZEJyaWdodFBpbmsgPSBDb2xvcigweEZGRTYwMDdFKTsKY29uc3QgQ29sb3IgbW9vZE5lb25QaW5rID0gQ29sb3IoMHhGRkZGMDBGRik7IC8vIEJlc3QgbW9vZApjb25zdCBMaXN0PENvbG9yPiBtb29kQ29sb3JzID0gWwogIG1vb2REZWVwUHVycGxlLAogIG1vb2RMaWdodFB1cnBsZSwKICBtb29kTWlkUGluaywKICBtb29kQnJpZ2h0UGluaywKICBtb29kTmVvblBpbmssCl07CiAgICBQSwMEFAAAAAAA/XsKW/4PWCF0BQAAdAUAAB4AAABsaWIvdXRpbHMvbWVzc2FnZV9zZXJ2aWNlLmRhcnQKaW1wb3J0ICdkYXJ0Om1hdGgnOwppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlci9zZXJ2aWNlcy5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnNoYXJlZF9wcmVmZXJlbmNlcy9zaGFyZWRfcHJlZmVyZW5jZXMuZGFydCc7CgpjbGFzcyBNZXNzYWdlU2VydmljZSB7CiAgc3RhdGljIGNvbnN0IExpc3Q8U3RyaW5nPiBjYXRlZ29yaWVzID0gWydNb3JuaW5nJywgJ01vdGl2YXRpb25hbCcsICdJbkpva2VzJ107CiAgc3RhdGljIE1hcDxTdHJpbmcsIExpc3Q8U3RyaW5nPj4gX21lc3NhZ2VzID0ge307CiAgc3RhdGljIFN0cmluZyBfc2VsZWN0ZWRDYXRlZ29yeSA9ICdNb3JuaW5nJzsKCiAgc3RhdGljIEZ1dHVyZTx2b2lkPiBsb2FkTWVzc2FnZXMoKSBhc3luYyB7CiAgICBmaW5hbCBwcmVmcyA9IGF3YWl0IFNoYXJlZFByZWZlcmVuY2VzLmdldEluc3RhbmNlKCk7CiAgICBfc2VsZWN0ZWRDYXRlZ29yeSA9IHByZWZzLmdldFN0cmluZygnbWVzc2FnZV9jYXRlZ29yeScpID8/ICdNb3JuaW5nJzsKICAgIGZpbmFsIGRhdGEgPSBhd2FpdCByb290QnVuZGxlLmxvYWRTdHJpbmcoJ2Fzc2V0cy90ZXh0cy9zcHJ1ZWNoZS50eHQnKTsKICAgIF9tZXNzYWdlcyA9IHsKICAgICAgJ01vcm5pbmcnOiBbXSwKICAgICAgJ01vdGl2YXRpb25hbCc6IFtdLAogICAgICAnSW5Kb2tlcyc6IFtdLAogICAgfTsKICAgIFN0cmluZyBjdXJyZW50Q2F0ZWdvcnkgPSAnJzsKICAgIGZvciAodmFyIGxpbmUgaW4gZGF0YS5zcGxpdCgnXG4nKSkgewogICAgICBpZiAobGluZS5zdGFydHNXaXRoKCdbJykgJiYgbGluZS5lbmRzV2l0aCgnXScpKSB7CiAgICAgICAgY3VycmVudENhdGVnb3J5ID0gbGluZS5zdWJzdHJpbmcoMSwgbGluZS5sZW5ndGggLSAxKTsKICAgICAgfSBlbHNlIGlmIChsaW5lLmlzTm90RW1wdHkgJiYgX21lc3NhZ2VzLmNvbnRhaW5zS2V5KGN1cnJlbnRDYXRlZ29yeSkpIHsKICAgICAgICBfbWVzc2FnZXNbY3VycmVudENhdGVnb3J5XSEuYWRkKGxpbmUpOwogICAgICB9CiAgICB9CiAgfQoKICBzdGF0aWMgRnV0dXJlPHZvaWQ+IHNldENhdGVnb3J5KFN0cmluZyBjYXRlZ29yeSkgYXN5bmMgewogICAgX3NlbGVjdGVkQ2F0ZWdvcnkgPSBjYXRlZ29yeTsKICAgIGZpbmFsIHByZWZzID0gYXdhaXQgU2hhcmVkUHJlZmVyZW5jZXMuZ2V0SW5zdGFuY2UoKTsKICAgIGF3YWl0IHByZWZzLnNldFN0cmluZygnbWVzc2FnZV9jYXRlZ29yeScsIGNhdGVnb3J5KTsKICB9CgogIHN0YXRpYyBTdHJpbmcgZ2V0UmFuZG9tTWVzc2FnZSgpIHsKICAgIGZpbmFsIG1lc3NhZ2VzID0gX21lc3NhZ2VzW19zZWxlY3RlZENhdGVnb3J5XSA/PyBbJ05vIG1lc3NhZ2VzIHlldCEnXTsKICAgIHJldHVybiBtZXNzYWdlc1tSYW5kb20oKS5uZXh0SW50KG1lc3NhZ2VzLmxlbmd0aCldOwogIH0KfQogICAgUEsDBBQAAAAAAP17CluvfsvtFQEAABUBAAAZAAAAYXNzZXRzL3RleHRzL3NwcnVlY2hlLnR4dApbTW9ybmluZ10KR3V0ZW4gTW9yZ2VuLCBkdSBTY2h1c3MKU2NodXNzQWxhcm0hIFRpbWUgdG8gc2hpbmUsIFN0ZWZmaSEKCltNb3RpdmF0aW9uYWxdCtGC0Ysg0YHQsNC80LDRjyDQutGA0LDRgdC40LLQsNGPINC20LXQvdGJ0LjQvdCwINCyINC80LjRgNC1LCBTdGVmZmnwn6WwClN0ZWZmaSBmb3IgUHJlc2lkZW50CgpbSW5Kb2tlc10KTGFzcyBoZXV0ZSBBYmVuZCBkdW1tIGdlaGVuIT8gTWFyYyB6YWhsdCBkaWUgRHJpbmtzIPCfjbgKU2Nod2FueiBpbiBBcnNjaCwgQmVzdGUhCiAgICBQSwMEFAAAAAAA/XsKW2uDCP/oCQAA6AkAAA0AAABsaWIvbWFpbi5kYXJ0CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6cHJvdmlkZXIvcHJvdmlkZXIuZGFydCc7CmltcG9ydCAncGFja2FnZTpzaGFyZWRfcHJlZmVyZW5jZXMvc2hhcmVkX3ByZWZlcmVuY2VzLmRhcnQnOwppbXBvcnQgJ3NjcmVlbnMvc3BsYXNoX3NjcmVlbi5kYXJ0JzsKaW1wb3J0ICdzZXJ2aWNlcy9hbGFybV9zZXJ2aWNlLmRhcnQnOwppbXBvcnQgJ3V0aWxzL2NvbnN0YW50cy5kYXJ0JzsKCnZvaWQgbWFpbigpIHsKICBydW5BcHAoCiAgICBNdWx0aVByb3ZpZGVyKAogICAgICBwcm92aWRlcnM6IFsKICAgICAgICBDaGFuZ2VOb3RpZmllclByb3ZpZGVyKGNyZWF0ZTogKF8pID0+IEFsYXJtU2VydmljZSgpKSwKICAgICAgXSwKICAgICAgY2hpbGQ6IE15QXBwKCksCiAgICApLAogICk7Cn0KCmNsYXNzIE15QXBwIGV4dGVuZHMgU3RhdGVmdWxXaWRnZXQgewogIEBvdmVycmlkZQogIF9NeUFwcFN0YXRlIGNyZWF0ZVN0YXRlKCkgPT4gX015QXBwU3RhdGUoKTsKfQoKY2xhc3MgX015QXBwU3RhdGUgZXh0ZW5kcyBTdGF0ZTxNeUFwcD4gewogIENvbG9yIF9zZWxlY3RlZENvbG9yID0gbW9vZE5lb25QaW5rOwoKICBAb3ZlcnJpZGUKICB2b2lkIGluaXRTdGF0ZSgpIHsKICAgIHN1cGVyLmluaXRTdGF0ZSgpOwogICAgX2xvYWRUaGVtZSgpOwogIH0KCiAgRnV0dXJlPHZvaWQ+IF9sb2FkVGhlbWUoKSBhc3luYyB7CiAgICBmaW5hbCBwcmVmcyA9IGF3YWl0IFNoYXJlZFByZWZlcmVuY2VzLmdldEluc3RhbmNlKCk7CiAgICBmaW5hbCBtb29kSW5kZXggPSBwcmVmcy5nZXRJbnQoJ21vb2RfaW5kZXgnKSA/PyA0OyAvLyBEZWZhdWx0IHRvIG5lb24gcGluawogICAgc2V0U3RhdGUoKCkgewogICAgICBfc2VsZWN0ZWRDb2xvciA9IG1vb2RDb2xvcnNbbW9vZEluZGV4XTsKICAgIH0pOwogIH0KCiAgRnV0dXJlPHZvaWQ+IF9zaG93TW9vZERpYWxvZygpIGFzeW5jIHsKICAgIGZpbmFsIG1vb2RJbmRleCA9IGF3YWl0IHNob3dEaWFsb2c8aW50PigKICAgICAgY29udGV4dDogY29udGV4dCwKICAgICAgYnVpbGRlcjogKGNvbnRleHQpID0+IEFsZXJ0RGlhbG9nKAogICAgICAgIGJhY2tncm91bmRDb2xvcjogQ29sb3JzLmJsYWNrLAogICAgICAgIHRpdGxlOiBUZXh0KCdXaGF04oCZcyB5b3VyIG1vb2QsIFN0ZWZmaT8nLCBzdHlsZTogVGV4dFN0eWxlKGNvbG9yOiBtb29kTmVvblBpbmspKSwKICAgICAgICBjb250ZW50OiBDb2x1bW4oCiAgICAgICAgICBtYWluQXhpc1NpemU6IE1haW5BeGlzU2l6ZS5taW4sCiAgICAgICAgICBjaGlsZHJlbjogTGlzdC5nZW5lcmF0ZSg1LCAoaW5kZXgpID0+IExpc3RUaWxlKAogICAgICAgICAgICB0aXRsZTogVGV4dChbJ0RlZXAgUHVycGxlJywgJ0xpZ2h0IFB1cnBsZScsICdNaWQgUGluaycsICdCcmlnaHQgUGluaycsICdOZW9uIFBpbmsnXVtpbmRleF0sCiAgICAgICAgICAgICAgICBzdHlsZTogVGV4dFN0eWxlKGNvbG9yOiBtb29kQ29sb3JzW2luZGV4XSkpLAogICAgICAgICAgICBvblRhcDogKCkgPT4gTmF2aWdhdG9yLnBvcChjb250ZXh0LCBpbmRleCksCiAgICAgICAgICApKSwKICAgICAgICApLAogICAgICApLAogICAgKTsKICAgIGlmIChtb29kSW5kZXggIT0gbnVsbCkgewogICAgICBmaW5hbCBwcmVmcyA9IGF3YWl0IFNoYXJlZFByZWZlcmVuY2VzLgdldEluc3RhbmNlKCk7CiAgICAgIGF3YWl0IHByZWZzLnNldEludCgnbW9vZF9pbmRleCcsIG1vb2RJbmRleCk7CiAgICAgIHNldFN0YXRlKCgpIHsKICAgICAgICBfc2VsZWN0ZWRDb2xvciA9IG1vb2RDb2xvcnNbbW9vZEluZGV4XTsKICAgICAgfSk7CiAgICB9CiAgfQoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpIHsKICAgIFdpZGdldHNCaW5kaW5nLmluc3RhbmNlLmFkZFBvc3RGcmFtZUNhbGxiYWNrKChfKSA9PiBfc2hvd01vb2REaWFsb2coKSk7CiAgICByZXR1cm4gTWF0ZXJpYWxBcHAoCiAgICAgIHRpdGxlOiAnU3RlZmZpIFdha2VBcHAnLAogICAgICB0aGVtZTogVGhlbWVEYXRhKAogICAgICAgIHByaW1hcnlDb2xvcjogX3NlbGVjdGVkQ29sb3IsCiAgICAgICAgc2NhZmZvbGRCYWNrZ3JvdW5kQ29sb3I6IENvbG9ycy5ibGFjaywKICAgICAgICBmb250RmFtaWx5OiAnRnV0dXJhJywKICAgICAgICBidXR0b25UaGVtZTogQnV0dG9uVGhlbWVEYXRhKAogICAgICAgICAgc2hhcGU6IFJvdW5kZWRSZWN0YW5nbGVCb3JkZXIoYm9yZGVyUmFkaXVzOiBCb3JkZXJSYWRpdXMuY2lyY3VsYXIoMTIpKSwKICAgICAgICApLAogICAgICAgIHRleHRUaGVtZTogVGV4dFRoZW1lKAogICAgICAgICAgYm9keVRleHQxOiBUZXh0U3R5bGUoY29sb3I6IENvbG9ycy53aGl0ZSwgZm9udFNpemU6IDE4KSwKICAgICAgICAgIGhlYWRsaW5lNjogVGV4dFN0eWxlKGNvbG9yOiBfc2VsZWN0ZWRDb2xvciwgZm9udFNpemU6IDI0LCBmb250V2VpZ2h0OiBGb250V2VpZ2h0LmJvbGQpLAogICAgICAgICksCiAgICAgICksCiAgICAgIGhvbWU6IFNwbGFzaFNjcmVlbigpLAogICAgKTsKICB9Cn0KICAgIFBLAwQUAAAAAAD9ewpba4MI/+gJAADoCQAADQAAAAAAAAAAAAAAgAEGCwAAbGliL3NjcmVlbnMvc3BsYXNoX3NjcmVlbi5kYXJ0CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6YXVkaW9wbGF5ZXJzL2F1ZGlvcGxheWVycy5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvZm91bmRhdGlvbi5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnZpYnJhdGUvdmlicmF0ZS5kYXJ0JzsKaW1wb3J0ICd1dGlscy9jb25zdGFudHMuZGFydCc7CmltcG9ydCAndXRpbHMvbWVzc2FnZV9zZXJ2aWNlLmRhcnQnOwppbXBvcnQgJ3NjcmVlbnMvaG9tZV9zY3JlZW4uZGFydCc7CgpkYXJ0CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6YXVkaW9wbGF5ZXJzL2F1ZGlvcGxheWVycy5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnZsdXR0ZXIvZm91bmRhdGlvbi5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnZpYnJhdGUvdmlicmF0ZS5kYXJ0JzsKaW1wb3J0ICd1dGlscy9jb25zdGFudHMuZGFydCc7CmltcG9ydCAndXRpbHMvbWVzc2FnZV9zZXJ2aWNlLmRhcnQnOwppbXBvcnQgJ3NjcmVlbnMvaG9tZV9zY3JlZW4uZGFydCc7CgpjbGFzcyBTcGxhc2hTY3JlZW4gZXh0ZW5kcyBTdGF0ZWZ1bFdpZGdldCB7CiAgQG92ZXJyaWRlCiAgX1NwbGFzaFNjcmVlblN0YXRlIGNyZWF0ZVN0YXRlKCkgPT4gX1NwbGFzaFNjcmVlblN0YXRlKCk7Cn0KCmNsYXNzIF9TcGxhc2hTY3JlZW5TdGF0ZSBleHRlbmRzIFN0YXRlPFNwbGFzaFNjcmVlbj4gewogIFN0cmluZyBfbWVzc2FnZSA9ICcnOwogIGZpbmFsIEF1ZGlvUGxheWVyIF9hdWRpb1BsYXllciA9IEF1ZGlvUGxheWVyKCk7CgogIEBvdmVycmlkZQogIHZvaWQgaW5pdFN0YXRlKCkgewogICAgc3VwZXIuaW5pdFN0YXRlKCk7CiAgICBfcGxheVNwbGFzaFNvdW5kKCk7CiAgICBfbG9hZE1lc3NhZ2UoKTsKICAgIEZ1dHVyZS5kZWxheWVkKER1cmF0aW9uKHNlY29uZHM6IDMpLCAoKSB7CiAgICAgIE5hdmlnYXRvci5wdXNoUmVwbGFjZW1lbnQoY29udGV4dCwgTWF0ZXJpYWxQYWdlUm91dGUoYnVpbGRlcjogKF8pID0+IEdvbWVTY3JlZW4oKSk7Ci   ..."

    # Directory to extract the ZIP contents into
    output_directory = "steffi_wakeapp"

    if not base64_string or base64_string == "HIER_DEN_GESAMTEN_BASE64_STRING_EINFÜGEN":
        raise SystemExit(
            "Please paste the full base64 string into 'base64_string' before running."
        )

    os.makedirs(output_directory, exist_ok=True)

    # Normalize base64: strip whitespace/newlines, remove data: prefix, fix padding
    normalized_b64 = base64_string.strip()
    if normalized_b64.startswith("data:"):
        try:
            normalized_b64 = normalized_b64.split(",", 1)[1]
        except Exception:
            pass
    normalized_b64 = "".join(normalized_b64.split())
    missing_padding = len(normalized_b64) % 4
    if missing_padding:
        normalized_b64 += "=" * (4 - missing_padding)

    try:
        zip_bytes = base64.b64decode(normalized_b64)
    except Exception as decode_error:  # noqa: BLE001 - broad for user convenience
        raise SystemExit(f"Failed to decode base64 input: {decode_error}")

    zip_buffer = BytesIO(zip_bytes)

    try:
        with zipfile.ZipFile(zip_buffer, "r") as zip_ref:
            zip_ref.extractall(output_directory)
    except zipfile.BadZipFile as bad_zip_error:
        raise SystemExit(f"Decoded data is not a valid ZIP file: {bad_zip_error}")
    except Exception as extract_error:  # noqa: BLE001 - broad for user convenience
        raise SystemExit(f"Failed to extract ZIP contents: {extract_error}")

    print(f"Extraction complete. Files written to '{output_directory}'.")


if __name__ == "__main__":
    main()

